language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# The extra env vars are for pyliblo
    
install:  "sudo apt-get install liblo0 liblo0-dev; C_INCLUDE_PATH=/usr/local/include LIBRARY_PATH=/usr/local/lib python setup.py install"


# command to run tests
script: nosetests tests
