"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
sys.setrecursionlimit(1500)

from setuptools import setup

APP = ['src/main.py']
DATA_FILES = ['protocols', 'img', 'recordings']
OPTIONS = {
        'argv_emulation': True,
        'includes': ['sip', 'numpy', 'PyQt4'],
        'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtNetwork', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest', 'PyQt4.QtWebKit', 'PyQt4.QtXml', 'PyQt4.phonon',
            'PyQt4.uic.port_v3']
            }


setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app', 'pyqtgraph', 'pyliblo'],
        )
